import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  { id: 'todos', name: 'Todos' },
  { id: 'promocoes', name: 'Promoções' },
  { id: 'medicamentos', name: 'Medicamentos' },
  { id: 'higiene', name: 'Higiene' },
  { id: 'beleza', name: 'Beleza' },
  { id: 'infantil', name: 'Infantil' },
  { id: 'vitaminas', name: 'Vitaminas' },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Dorflex 50 Comprimidos',
    description: 'Analgésico e relaxante muscular. Indicado para dores de cabeça e dores musculares.',
    price: 24.90,
    promotionalPrice: 19.99,
    category: 'medicamentos',
    image: 'https://picsum.photos/seed/dorflex/400/400',
    indications: 'Dor de cabeça, Dor muscular',
  },
  {
    id: '2',
    name: 'Vitamina C 1g Efervescente',
    description: 'Suplemento vitamínico auxiliar do sistema imunológico. Tubo com 10 comprimidos.',
    price: 15.00,
    category: 'vitaminas',
    image: 'https://picsum.photos/seed/vitamina/400/400',
  },
  {
    id: '3',
    name: 'Fralda Pampers Premium G',
    description: 'Fralda descartável suave para a pele do bebê. Pacote com 30 unidades.',
    price: 69.90,
    promotionalPrice: 59.90,
    category: 'infantil',
    image: 'https://picsum.photos/seed/fralda/400/400',
  },
  {
    id: '4',
    name: 'Shampoo Dove Reconstrução',
    description: 'Shampoo para cabelos danificados. Reconstrói a fibra capilar em 7 dias.',
    price: 22.50,
    category: 'higiene',
    image: 'https://picsum.photos/seed/shampoo/400/400',
  },
  {
    id: '5',
    name: 'Protetor Solar FPS 60',
    description: 'Alta proteção contra raios UVA e UVB. Toque seco e oil-free.',
    price: 89.90,
    promotionalPrice: 75.00,
    category: 'beleza',
    image: 'https://picsum.photos/seed/sun/400/400',
  },
  {
    id: '6',
    name: 'Neosaldina 30 Drágeas',
    description: 'Medicamento com atividade analgésica e antiespasmódica.',
    price: 28.90,
    category: 'medicamentos',
    image: 'https://picsum.photos/seed/neo/400/400',
  },
  {
    id: '7',
    name: 'Leite em Pó Ninho Fases',
    description: 'Composto lácteo com prebióticos e vitaminas. Lata 400g.',
    price: 45.00,
    category: 'infantil',
    image: 'https://picsum.photos/seed/ninho/400/400',
  },
  {
    id: '8',
    name: 'Sabonete Líquido Facial',
    description: 'Limpeza profunda para pele oleosa. Remove o excesso de oleosidade.',
    price: 35.90,
    category: 'beleza',
    image: 'https://picsum.photos/seed/soap/400/400',
  },
  {
    id: '9',
    name: 'Multivitamínico Centrum',
    description: 'Suplemento vitamínico e mineral de A a Z. 60 comprimidos.',
    price: 120.00,
    promotionalPrice: 99.90,
    category: 'vitaminas',
    image: 'https://picsum.photos/seed/centrum/400/400',
  },
  {
    id: '10',
    name: 'Creme Dental Colgate Total 12',
    description: 'Proteção completa por 12 horas. Combate placas, tártaro e cáries.',
    price: 8.99,
    category: 'higiene',
    image: 'https://picsum.photos/seed/colgate/400/400',
  },
];